[package]
name = "rusty-craft-launcher"
version = "0.1.0"
authors = ["Cat Core <arthur.koalas@free.fr>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg_aliases = "0.1.1"
directories = "4.0.1"
